FROM alpine:3.12.2

RUN apk update && apk upgrade -U -a


RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

RUN mkdir /notificationproducer
COPY producer /notificationproducer
COPY notification_handler.properties  /notificationproducer

WORKDIR /notificationproducer

CMD ./producer

