apiVersion: v1
kind: Pod
metadata:
  name: producer
  namespace: kafka
spec:
  containers:
  - name: producer
    image: srikrishnabh/producer:1.0
    imagePullPolicy: IfNotPresent
#  nodeName: kubemaster-weave # test-purpose
