// Code generated by protoc-gen-go. DO NOT EDIT.
// source: notifier.proto

package notifier

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ChannelType int32

const (
	ChannelType_EMAIL ChannelType = 0
	ChannelType_SLACK ChannelType = 1
)

var ChannelType_name = map[int32]string{
	0: "EMAIL",
	1: "SLACK",
}
var ChannelType_value = map[string]int32{
	"EMAIL": 0,
	"SLACK": 1,
}

func (x ChannelType) String() string {
	return proto.EnumName(ChannelType_name, int32(x))
}
func (ChannelType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_notifier_abba352b96364161, []int{0}
}

//
type Notification struct {
	To                   string     `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	From                 string     `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Body                 string     `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Subject              string     `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Channels             []*Channel `protobuf:"bytes,5,rep,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_notifier_abba352b96364161, []int{0}
}
func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (dst *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(dst, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Notification) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Notification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Notification) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Notification) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Channel struct {
	Type                 ChannelType       `protobuf:"varint,1,opt,name=type,proto3,enum=notifier.ChannelType" json:"type,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Channel) Reset()         { *m = Channel{} }
func (m *Channel) String() string { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()    {}
func (*Channel) Descriptor() ([]byte, []int) {
	return fileDescriptor_notifier_abba352b96364161, []int{1}
}
func (m *Channel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Channel.Unmarshal(m, b)
}
func (m *Channel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Channel.Marshal(b, m, deterministic)
}
func (dst *Channel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Channel.Merge(dst, src)
}
func (m *Channel) XXX_Size() int {
	return xxx_messageInfo_Channel.Size(m)
}
func (m *Channel) XXX_DiscardUnknown() {
	xxx_messageInfo_Channel.DiscardUnknown(m)
}

var xxx_messageInfo_Channel proto.InternalMessageInfo

func (m *Channel) GetType() ChannelType {
	if m != nil {
		return m.Type
	}
	return ChannelType_EMAIL
}

func (m *Channel) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Notification)(nil), "notifier.Notification")
	proto.RegisterType((*Channel)(nil), "notifier.Channel")
	proto.RegisterMapType((map[string]string)(nil), "notifier.Channel.MetadataEntry")
	proto.RegisterEnum("notifier.ChannelType", ChannelType_name, ChannelType_value)
}

func init() { proto.RegisterFile("notifier.proto", fileDescriptor_notifier_abba352b96364161) }

var fileDescriptor_notifier_abba352b96364161 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x9d, 0xfe, 0x48, 0xb9, 0x68, 0x53, 0x6f, 0x34, 0x99, 0xb8, 0x91, 0xe0, 0x06, 0x4d,
	0xec, 0x02, 0x37, 0x46, 0x56, 0x84, 0xb0, 0x30, 0x82, 0x8b, 0xea, 0x0b, 0x4c, 0xcb, 0x10, 0xab,
	0x30, 0xd3, 0x94, 0x8b, 0xc9, 0x3c, 0x85, 0x6f, 0xe2, 0x33, 0x9a, 0x4e, 0x4b, 0xa3, 0x61, 0x77,
	0xce, 0x37, 0xe7, 0x66, 0x4e, 0x0e, 0x84, 0x4a, 0x53, 0xbe, 0xca, 0x65, 0x19, 0x17, 0xa5, 0x26,
	0x8d, 0xc1, 0xde, 0x0f, 0xbe, 0x19, 0x9c, 0xbc, 0x58, 0x93, 0x09, 0xca, 0xb5, 0xc2, 0x10, 0x1c,
	0xd2, 0x9c, 0xf5, 0xd9, 0xb0, 0x9b, 0x38, 0xa4, 0x11, 0xc1, 0x5b, 0x95, 0x7a, 0xc3, 0x1d, 0x4b,
	0xac, 0xae, 0x58, 0xaa, 0x97, 0x86, 0xbb, 0x35, 0xab, 0x34, 0x72, 0xe8, 0x6c, 0x77, 0xe9, 0x87,
	0xcc, 0x88, 0x7b, 0x16, 0xef, 0x2d, 0xde, 0x41, 0x90, 0xbd, 0x0b, 0xa5, 0xe4, 0x7a, 0xcb, 0xfd,
	0xbe, 0x3b, 0xec, 0x8d, 0xce, 0xe2, 0xb6, 0xcf, 0xb4, 0x7e, 0x49, 0xda, 0xc8, 0xe0, 0x87, 0x41,
	0xa7, 0xa1, 0x78, 0x03, 0x1e, 0x99, 0x42, 0xda, 0x3a, 0xe1, 0xe8, 0xe2, 0xe0, 0xec, 0xcd, 0x14,
	0x32, 0xb1, 0x11, 0x1c, 0x43, 0xb0, 0x91, 0x24, 0x96, 0x82, 0x04, 0x77, 0xec, 0x2f, 0x57, 0x07,
	0xf1, 0x78, 0xd1, 0x24, 0x66, 0x8a, 0x4a, 0x93, 0xb4, 0x07, 0x97, 0x63, 0x38, 0xfd, 0xf7, 0x84,
	0x11, 0xb8, 0x9f, 0xd2, 0x34, 0x33, 0x54, 0x12, 0xcf, 0xc1, 0xff, 0x12, 0xeb, 0x9d, 0x6c, 0x86,
	0xa8, 0xcd, 0xa3, 0xf3, 0xc0, 0x6e, 0xaf, 0xa1, 0xf7, 0xa7, 0x0e, 0x76, 0xc1, 0x9f, 0x2d, 0x26,
	0x4f, 0xf3, 0xe8, 0xa8, 0x92, 0xaf, 0xf3, 0xc9, 0xf4, 0x39, 0x62, 0xe9, 0xb1, 0x1d, 0xfe, 0xfe,
	0x37, 0x00, 0x00, 0xff, 0xff, 0x3c, 0x70, 0x49, 0x5a, 0x8a, 0x01, 0x00, 0x00,
}
